### ISSUE TITLE
Server won't launch with 'npm run srv-dev'

### ISSUE THREAD

**Issue by nicolasvienot** [jeremie-gauthier/Red-Tetris#1]
The server doesn't launch with `npm run srv-dev`
Actual command is : `DEBUG=tetris:* babel-watch -w src src/server/main.js`

-> Error says that the babel/core version needs to be >7.0.0 ans that we have 6.23.0.

**Comment by jeremie-gauthier** [comment]
Fix confirmed

**Comment by jeremie-gauthier** [comment]
Plus I added cache policy on webpack which reduced compile time from 10s to 2s on my computer.
I merge with develop
