### ISSUE TITLE
Async issue on Gravity Timer

### ISSUE THREAD

**Issue by jeremie-gauthier** [jeremie-gauthier/Red-Tetris#14]
I tried to enhance Tetris Game as marked in #13 

I have worked on the point that say the gravity timer should never stop on user action (e.g. rotation)

But I have found an issue that seems to be correlated with async state update.

Sometimes, when you want to make a rotation of the piece, it rotate well, but when the gravity action happens, it goes back to its original position (reverse rotate) one case down.

This happened with a gravity timer of 250ms.

What can possibly happens is that both actions plays concurrently with the same state of the piece and modify it the way they are programmed to.

I am not sure how to resolve this bug right now.

I wonder if working with a mutable ref of the piece could do it.

What do you think ?

**Comment by nicolasvienot** [comment]
How can I reproduce this?
I tried playing with autoMoveTimer.stop(); and autoMoveTimer.start(); but didn't manage to get the piece continue to go down with the rotation for example.
Does everything happen in useTetrisGame.js?

**Comment by jeremie-gauthier** [comment]
I'll work on recreating a version with this issue
