### ISSUE TITLE
Manage end of game

### ISSUE THREAD

**Issue by jeremie-gauthier** [jeremie-gauthier/Red-Tetris#40]
Gestion de la fin de game (vider le store game, vider "game" dans le store global, permettre de rejouer, retour sur un lobby propre, passage du lobby a isPlaying:false)

When you click "Return to Home" during a game and you reconnect with an other uname, you can't create lobby: `You already have an active lobby`

If all players Click "return to Home" the should should disappear (or at least not set to 'in game' state)

**Comment by jeremie-gauthier** [comment]
The followings parts has been solved in GH-37:

- retour sur un lobby propre
- passage du lobby a isPlaying:false
- When you click "Return to Home" during a game and you reconnect with an other uname, you can't create lobby: You already have an active lobby

**Comment by nicolasvienot** [comment]
Improved GH-37 :
Lobby to isPlaying:false server side DONE
At end of game, it will set the winner as the owner if he is still there

**Comment by nicolasvienot** [comment]
Might need to be done :
Keep the game object in GameState until the click on button, in order to display the score of all the players
