### ISSUE TITLE
Manage winner of a game

### ISSUE THREAD

**Issue by jeremie-gauthier** [jeremie-gauthier/Red-Tetris#44]
Modification du setWinner cote serveur pour gerer un score egal ou un score de 0

**Comment by nicolasvienot** [comment]
bug :
- Server does not declare a winner???
- If we play a game at 2 players and the first player just spam space and the other player doesnt do anything :
When player1 loses, if he touch space again, it will name the player2 as winner.

**Comment by nicolasvienot** [comment]
On further consideration, the debounce might be a problem here too. At least for the bugs :
-> When player spam space, the score and board is not sent. So when the player lose, the informations were not updated, and the server has issues setting set a winner.

**Comment by nicolasvienot** [comment]
Need to check : server not setting winner ?
