### ISSUE TITLE
Feature `Join Game`

### ISSUE THREAD

**Issue by jeremie-gauthier** [jeremie-gauthier/Red-Tetris#50]
Connect the Join Game button to back

**Comment by nicolasvienot** [comment]
For this issue :
-> Disable the button if there is no lobby available (no lobby, all lobby are playing/full)
-> Select the "best" lobby to join and send a :
    socket.emit(LOBBY.SUBSCRIBE, {
      lobbyId,
      playerId: state.player.id,
    });
