### ISSUE TITLE
Bug translate on prod 

### ISSUE THREAD

**Issue by nicolasvienot** [jeremie-gauthier/Red-Tetris#74]
On prod, all the accents are deads 😔

**Comment by nicolasvienot** [comment]
![Uploading Capture d’écran du 2020-11-11 05-04-05.png…]()

**Comment by jeremie-gauthier** [comment]
Isn't it an encode issue with the webserver ?

**Comment by nicolasvienot** [comment]
I added "charset UTF-8;" in the http section of /etc/nginx/nginx.conf

Looks like its working now.
Might need to put the nginx.conf in resources of project just as a reminder for next projects
