### ISSUE TITLE
Data architecture + persistence

### ISSUE THREAD

**Issue by nicolasvienot** [jeremie-gauthier/Red-Tetris#9]
Let's talk about data architecture and the persistence associated.

**Comment by jeremie-gauthier** [comment]
In front some data will be stored globally (Top Level Context) and others will just be sent from parents to children or with local context.

Context is not magic, it works like other kind of in-component state and each time you refresh your browser it comes with a data loss. But maybe we could do something to fetch some data back from the server if the socket ID doesn't change in the meanwhile.

#### Global State

To know what should be put in Global State I usually ask myself **"What data won't change ?"** and **"What data need to be known by a sufficient number of components (that it would be painful and unmaintainable to declare it everywhere)?"**

- Player name
- Current Lobby ??
- Data related to account (bonus part)

#### Local State
- Tetris pieces and score (in game)
- Lobby chat (bonus part)
