### ISSUE TITLE
Bonuses

### ISSUE THREAD

**Issue by nicolasvienot** [jeremie-gauthier/Red-Tetris#90]
### Let's list the bonuses that we could present :

- Dockerized app for development and production
- Deployed as https on own server : https://redtetris.co
- Full website traduction
- Levels on game
- Scoring system
- Real-time opponent game board
- Can play with 4 oppponents
- Architecture
- Project management (PR, issues, GH...)
- Redis
- Kick player
- Disconnection handling
- Ready/Not Ready in Lobby
- Sound
- Game and sound are quicker on level up
- Real-time chat on lobby and in game
- Helper
- Notifications on chat

**Comment by jeremie-gauthier** [comment]
Definitely agree with your interrogations: Levels, Kick player and Disconnection should be presented as bonuses :rocket: :rocket: 

The Score during the game and the small end game leaderboard should also be considered bonuses.
Edit: (I edited your comment to have all infos at the top of this issue)

**Comment by nicolasvienot** [comment]
+ Added ready/not ready

**Comment by nicolasvienot** [comment]
+ Chat

**Comment by nicolasvienot** [comment]
+ helper
+ notifications on chat

**Comment by jeremie-gauthier** [comment]
@all-contributors please add @nicolasvienot  for code

**Comment by jeremie-gauthier** [comment]
@all-contributors please add @jeremie-gauthier for code
