### ISSUE TITLE
Add board on setLoser because of debounce

### ISSUE THREAD

**Issue by nicolasvienot** [jeremie-gauthier/Red-Tetris#91]
Since I put a debounce on the SEND_SCORE and SEND_BOARD to avoid too many request and dispatch on server/client, the boards and scores might not be updated when a player lose.
This needs to be fixed by either adding better debounce or adding the score and the board in GET_LOSER.

**Comment by jeremie-gauthier** [comment]
@nicolasvienot 
Is this ticket up to date ? Or has it been solved with your PR that had implemented the throttle and removed the debounce ?

**Comment by nicolasvienot** [comment]
Not fixing the board at end of game
